name: css_stranbys
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.5.5'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  get: ^4.6.5
  dio: ^5.2.1+1
  device_info_plus: ^9.0.0
  path_provider: ^2.0.11
  package_info_plus: ^4.0.2
  dropdown_button2: ^2.1.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0
  sizer: ^2.0.15
  shared_preferences: ^2.0.15
  loading_animation_widget: ^1.2.0+4
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0
  flutter_bounceable: ^1.1.0
  animate_do: ^3.0.2
  lottie: ^2.3.0
  mobile_scanner: ^3.4.1
  image_picker: ^1.0.0
  honeywell_scanner: ^6.0.0

dev_dependencies:
  build_runner: ^2.4.0  # Add this line
  freezed: ^2.2.0
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/